version: '3.7'

services:

  reverse-proxy:
    image: traefik:v2.7
    command:
      # Unconmmend the following line to enable debug mode
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # Backend service for the Name Game
  namegame:
    build:
      context: .  
    image: psanders/namegame:latest
    restart: always
    expose:
      - 3000
    # Declaring the user list
    #
    # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
    # To create user:password pair, it's possible to use this command:
    # echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
    #
    # Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
    labels:
      - "traefik.http.middlewares.auth.basicauth.users=namegame:$$2y$$05$$WbI88g.ej1KUwaNzUkhReuEJssVzc7Ml/V/kV5AxiGzQqBEJFLnoS"
      - "traefik.http.routers.namegame.middlewares=auth@docker"
      - "traefik.http.routers.namegame.rule=Host(`namegame.docker.localhost`)"      
    environment:
      - PROFILE_API_URL
      - REDIS_HOST
      - REDIS_PORT
      - LOGS_LEVEL
      - LOGS_TRANSPORT

  # Redis store
  redis:
    image: redis:6.0.3-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
